// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiEqJbVJmWhTMZqqwFZIcXHhX91g1-WRg',
    appId: '1:840797312247:web:4f03625014bc4790ceeff2',
    messagingSenderId: '840797312247',
    projectId: 'todolist-15164',
    authDomain: 'todolist-15164.firebaseapp.com',
    storageBucket: 'todolist-15164.firebasestorage.app',
    measurementId: 'G-KEMVBMW120',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbh7uNcAWUyDktc0TCqaUKha91wJlixCY',
    appId: '1:840797312247:android:af396a3e55065977ceeff2',
    messagingSenderId: '840797312247',
    projectId: 'todolist-15164',
    storageBucket: 'todolist-15164.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-E-UJc5eGOAVQiN5jk38zk6og5VQfZ9U',
    appId: '1:840797312247:ios:f127b9e80b5a4dfeceeff2',
    messagingSenderId: '840797312247',
    projectId: 'todolist-15164',
    storageBucket: 'todolist-15164.firebasestorage.app',
    iosBundleId: 'com.example.todoListAkhir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-E-UJc5eGOAVQiN5jk38zk6og5VQfZ9U',
    appId: '1:840797312247:ios:f127b9e80b5a4dfeceeff2',
    messagingSenderId: '840797312247',
    projectId: 'todolist-15164',
    storageBucket: 'todolist-15164.firebasestorage.app',
    iosBundleId: 'com.example.todoListAkhir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiEqJbVJmWhTMZqqwFZIcXHhX91g1-WRg',
    appId: '1:840797312247:web:7611dec7e6760a36ceeff2',
    messagingSenderId: '840797312247',
    projectId: 'todolist-15164',
    authDomain: 'todolist-15164.firebaseapp.com',
    storageBucket: 'todolist-15164.firebasestorage.app',
    measurementId: 'G-4222LK97PY',
  );
}
